WiP: adding redux-cli custom blueprints
SlobodaStudio/tutorium-web pull request #2
Opened 2017-05-06 20:33 UTC by vittorius

2017-05-10 08:28 UTC, roman-holovin requested changes
My general recommendation will be eslint configuration. Default config from CRA are too lax. `eslint-config-airbnb` is more strict and has many additional rules enabled. This will ensure code style consistency.

2017-05-10 08:28 UTC, dantix commented on blueprints/smart/files/__root__/__smart__/__name__.js
> +const mapStateToProps = (state) => {
It is more convenient to use short forms of the map functions. Also, these should be placed at the top the file. This way you can see data flow before component code that uses this data.

2017-05-10 08:28 UTC, dantix commented on blueprints/dumb/files/__root__/__dumb__/__name__.js
> +import React, { Component, PropTypes } from 'react'
Starting with react 15.5.5 `PropTypes` are now separate module, this code will issue a warning.
https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html#migrating-from-react.proptypes

2017-05-10 08:28 UTC, dantix commented on blueprints/duck/index.js
> +const entityNameLocals = require('../util').entityNameLocals;
Either you place semicolons everywhere or omit them entirely.
You can define eslint rule about semicolons and use `eslint ---fix` to make it consistent everywhere

2017-05-10 08:28 UTC, dantix commented on blueprints/duck/index.js
> +  locals(options) {
This function is redundant.

2017-05-10 08:28 UTC, dantix commented on blueprints/duck/index.js
> +        return `redux/modules${separator}${options.locals.entityPath}`;
This `return`is redundant

2017-05-10 08:28 UTC, dantix commented on blueprints/form/files/__root__/__form__/__name__.js
> +  validate
Usage of trailing comma is inconsistent.

2017-05-10 08:28 UTC, dantix commented on blueprints/util.js
> +      (locals, variant) => Object.assign(locals, { [`${variant}EntityName`]: normalizeCasing(epInfo.baseName, variant)}),
Inconsistent usage of spacing in object declaration

2017-05-13 21:25 UTC, vittorius commented on blueprints/form/files/__root__/__form__/__name__.js
> +  validate
Made consistent with ESLint config.

2017-05-22 08:42 UTC, roman-holovin approved these changes

2017-05-22 08:43 UTC, merged