test: Add snapshot tests for Events and Day component
SlobodaStudio/tutorium-web pull request #6
Opened 2017-05-12 14:19 UTC by limoozyn

Add snapshot tests for Events and Day component
--

**Checklist**

- [X] [YouTrack ticket](https://tutorium.myjetbrains.com/youtrack/issue/EDU-7) created
- [X] ready to review

**Why?**

To avoid accidental change of components

2017-05-12 14:21 UTC, roman-holovin requested changes
Where are snapshot files?

2017-05-12 14:30 UTC, roman-holovin approved these changes

2017-05-12 14:33 UTC, vittorius requested changes

2017-05-12 14:33 UTC, vittorius commented on src/test/components/Day/Day.test.js
>  import Day from '../../../components/Day/Day'
Why not an absolute import? Our Webpack config should treat the `src/` as a root dir.

2017-05-12 14:33 UTC, vittorius commented on src/test/components/Day/Day.test.js
>  import { List, ListItem, ListSubHeader} from 'react-toolbox/lib/list'
`ListSubHeader}`: missing space before the bracket

2017-05-12 14:33 UTC, vittorius commented on src/test/containers/Events/Events.test.js
>  import { List, ListItem, ListSubHeader} from 'react-toolbox/lib/list'
ListSubHeader}: missing space before the bracket

2017-05-12 14:33 UTC, vittorius commented on src/test/containers/Events/Events.test.js
>  import Events from '../../../containers/Events/Events'
The same thing with relative imports.

2017-05-13 21:12 UTC, vittorius approved these changes

2017-05-15 07:05 UTC, merged